name: NC-DataEng-ETL-Project-CICD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Create environment
        run: make requirements
      - name: Run security checks
        run: make run-security
      - name: Run formatter and tests
        run: make run-checks

  #s3 files should never be destroyed once created and 
  #application has been deployed...
  #potentially store s3 terraform in a different working directory
  #(terraform_s3)?? But does this link up everything correctly?
  deploy-terraform:
    name: deploy-terraform
    runs-on: ubuntu-latest
    environment: dev
    needs: run-tests
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v4
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Terraform plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform format
        working-directory: terraform
        run: terraform fmt
      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve